export * from './edit-location-modal/edit-location-modal.component';
export * from './edit-location-modal/edit-location-modal.module';
export * from './edit-user-modal/edit-user-modal.component';
export * from './edit-user-modal/edit-user-modal.module';
export * from './change-password-user-modal/change-password-user-modal.component';
export * from './change-password-user-modal/change-password-user-modal.module';
export * from './uni-confirm-modal/uni-confirm-modal.module';
//export * from './add-to-order-modal/add-to-order-modal.module';
//export * from './add-to-order-modal/add-to-order-modal.component';